name: rrms
description: Resident relations management app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  bottom_picker: ^2.8.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.5
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  expandable: ^5.0.1
  file_picker: ^8.0.3
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  fluttertoast: ^8.2.5
  flutter_cached_pdfview: ^0.4.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_paypal_payment: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.1.1
  image_cropper: ^5.0.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  octo_image: ^2.0.0
  open_file_plus: ^3.4.1+1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  rest_api_client: ^2.2.24
  shimmer: ^3.0.0
  storage_repository: ^1.1.14
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  webview_flutter: ^4.7.0
  wechat_assets_picker: ^9.0.3
  

dev_dependencies:
  analyzer: ^6.7.0
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flugger: ^0.1.8
  

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/WorkSans-Italic.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic
        
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 24
  windows:
    generate: true
    image_path: "assets/logo.jpg"
    icon_size: 48 

flutter_native_splash:
  color: "#000000"
  image: assets/splash.jpeg
  android_12:
    image: assets/splash.jpeg
    icon_background_color: "#000000"
  web: false