// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQoIU0f7TeDA5IAZ7BTyxFx6QV3QJWKb8',
    appId: '1:1065194357789:android:10074071b5de7a7b96b2f4',
    messagingSenderId: '1065194357789',
    projectId: 'rrms-d79d6',
    storageBucket: 'rrms-d79d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFwiZ5svfFfe9OyTzm0go5bbxYUUqUa-4',
    appId: '1:1065194357789:ios:c472e969c6d5650296b2f4',
    messagingSenderId: '1065194357789',
    projectId: 'rrms-d79d6',
    storageBucket: 'rrms-d79d6.appspot.com',
    iosBundleId: 'com.rs2.rrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOt1ALUXC1vum-LXxcwEF8Q4Ei7aPd1fA',
    appId: '1:1065194357789:web:fb52ea8bafd3ae7296b2f4',
    messagingSenderId: '1065194357789',
    projectId: 'rrms-d79d6',
    authDomain: 'rrms-d79d6.firebaseapp.com',
    storageBucket: 'rrms-d79d6.appspot.com',
  );
}
